config/routes.rb
Rails.application.routes.draw do

    root to: 'posts#index'
    # get '/comments', to: 'comments#index'
    resources :posts do
        resources :comments
    end
    resources :posts do
        resources :tags
    end
    resources :categories do
        resources :tags
    end

    resources :posts do
        member do
            post 'bump_up'
            post 'bump_down'
        end
    end

    resources :tags do
        member do
            post 'add_tag'
        end
    end

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :tags
    has_many :posts, through: :tags
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    has_many :tags
    has_many :categories, through: :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    belongs_to :post
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.create!(category_params)
        redirect_to @category
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        @category.update(category_params)
        redirect_to @category
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to categories_path
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index
        @comments = Comment.all
    end

    def show
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
    end

    def new
        @post = Post.find(params[:post_id])
        @comment = Comment.new
    end

    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.create!(comment_params.merge(post: @post))
        redirect_to post_path(@post)
    end

    def edit
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
    end

    def update
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
        @comment = @post.comments.update(@comment, comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to posts_path(@post)
    end

    private
    def comment_params
        params.require(:comment).permit(:content, :commenter, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
        @tag = Tag.new
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.create!(post_params)
        redirect_to @post
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        redirect_to @post
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    def bump_up
        @post = Post.find(params[:id])
        temp = @post.bumps + 1
        Post.update(@post, :bumps => temp)
        redirect_to (:back)
    end

    def bump_down
        @post = Post.find(params[:id])
        temp = @post.bumps - 1
        Post.update(@post, :bumps => temp)
        redirect_to (:back)
    end

    private
    def post_params
        params.require(:post).permit(:subject, :poster, :body, :bumps)
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def new
        @post = Post.find(params[:post_id])
        @tag = Tag.new
    end

    def create
        @post = Post.find(params[:post_id])
        @tag = Tag.create!(tag_params)
        redirect_to post_path(@post)
    end

    def update
        @post = Post.find(params[:post_id])
        @tag = Tag.find(params[:id])
        @tag = @post.tags.update(@tag, tag_params.merge(post: @post))
        redirect_to post_path(@post)
    end

    def add_tag
        if Category.all.detect {|f| f["name"] == params[:tag][:name] }
            if Tag.all.detect {|f| f["name"] == params[:tag][:name] }
                puts "cat and tag exist, nothing created"
            else
                cat_name = params[:tag][:name]
                cat_id = Category.find_by(name: cat_name).id
                @tag = Tag.create!(name: params[:tag][:name], post_id: params[:tag][:post_id], category_id: cat_id)
                puts "only cat exists, created tag"
            end
        else
            if Tag.all.detect {|f| f["name"] == params[:tag][:name] }
                @category = Category.create!(name: params[:tag][:name])
                puts "only tag exists, created cat"
            else
                @category = Category.create!(name: params[:tag][:name])
                @tag = Tag.create!(name: params[:tag][:name], post_id: params[:tag][:post_id], category: @category)
                puts "neither exist, created both"
            end
        end
        redirect_to (:back)
    end

    private
    def tag_params
        params.require(:tag).permit(:name, :post_id, :category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>

<% end %>

app/views/categories/index.html.erb
index

app/views/categories/new.html.erb
<h2><%= link_to "Categories", categories_path %></h2>

<h3>New Category</h3>

<%= render 'form' %>

app/views/categories/show.html.erb
<h3>Posts</h3>
<ul>
    <% @category.posts.sort_by{|x| [x.created_at] }.reverse.each do |post| %>
    <li>
        <%= link_to "#{post.subject} - #{post.poster}", post_path(post) %>
    </li>
    <% end %>
</ul>

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :commenter %>
  <%= f.text_field :commenter %>

  <%= f.submit %>

<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render 'form' %>

<%= link_to 'Delete!', post_comment_path(@post, @comment), method: :delete, class: 'delete' %>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav>
        <h2><a href="/posts"><%= image_tag "scribble.png" %></a></h2>
        <h4><a href="javascript:history.back()">Back</a></h4>
    </nav>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <%= f.label :subject %>
  <%= f.text_field :subject %>

  <%= f.label :poster %>
  <%= f.text_field :poster %>
<br>
<br>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<% end %>

app/views/posts/_post.html.erb
<ul>
    <li>
        <%= post.bumps %> &nbsp
        <a href="/posts/<%= post.id %>">
            <%= post.subject %> - <%= post.poster%>
        </a>
        &nbsp(<%= link_to "+", bump_up_post_path(post), method: :post %>)
        &nbsp/
        &nbsp(<%= link_to "-", bump_down_post_path(post), method: :post %>)
    </li>
</ul>

app/views/posts/edit.html.erb
<h2><%= link_to "Posts", posts_path %></h2>

<h3>New Post</h3>

<%= render 'form' %>

<%= link_to 'Delete!', post_path(@post), method: :delete, class: 'delete' %>

app/views/posts/index.html.erb
<h2>Posts <a href="/posts/new">(+)</a></h2>

<%= render partial: "post", collection: @posts.sort_by{|x| [x.created_at] }.reverse %>

app/views/posts/new.html.erb
<h2><%= link_to "Posts", posts_path %></h2>

<h3>New Post</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.subject %> <a href="/posts/<%= @post.id %>/edit">(edit)</a>&nbsp&nbsp<%= @post.bumps %>&nbsp<%= link_to "+", bump_up_post_path(@post), method: :post %>&nbsp<%= link_to "-", bump_down_post_path(@post), method: :post %></h2>
<h4><%= @post.poster %></h4>

<p><%= @post.body %></p>

<h3>Comments <%= link_to "(+)", new_post_comment_path(@post) %></h3>
<ul>
  <% @post.comments.reverse.each do |comment| %>
    <li>
      <%= comment.content %> <%= link_to "(edit)", edit_post_comment_path(@post, comment) %>
      <br>
      - <%= comment.commenter %>
    </li>

  <% end %>
</ul>

<h3>Categories</h3>
<ul>
    <% @post.categories.each do |category| %>
    <li>
        <%= link_to "#{category.name}", category_path(category) %>
    </li>
    <% end %>
</ul>

<h5>
<%= form_for @tag, url: "/tags/@tag/add_tag" do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <%= f.submit %>
<% end %>
</h5>

app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :post_id %>
    <%= f.text_field :post_id %>

    <%= f.submit %>

<% end %>

app/views/tags/new.html.erb
<h2>New Tag</h2>

<%= render 'form' %>